### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by Nineeeeeeeee** [ethan-prime/tiktok-name-checker-v2#1]
Hey, anyway you can add a way to add a list in like usernames.txt

Not enough space to paste all the usernames in

**Comment by Nineeeeeeeee** [comment]
Thank you! 
And by any chance would you be able to make the users spit into a available.txt the ones that pop up?

**Comment by ethan-prime** [comment]
Of course. Don’t know how I didn’t think of this. Thank you for the suggestion, I’ll implement in within the next hour or so.

**Comment by Nineeeeeeeee** [comment]
Thank you!!

**Comment by ethan-prime** [comment]
It should be implemented now. :)
